/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerimaRouteImport } from './routes/terima'
import { Route as PesanRouteImport } from './routes/pesan'
import { Route as IndexRouteImport } from './routes/index'

const TerimaRoute = TerimaRouteImport.update({
  id: '/terima',
  path: '/terima',
  getParentRoute: () => rootRouteImport,
} as any)
const PesanRoute = PesanRouteImport.update({
  id: '/pesan',
  path: '/pesan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pesan': typeof PesanRoute
  '/terima': typeof TerimaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pesan': typeof PesanRoute
  '/terima': typeof TerimaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pesan': typeof PesanRoute
  '/terima': typeof TerimaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pesan' | '/terima'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pesan' | '/terima'
  id: '__root__' | '/' | '/pesan' | '/terima'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PesanRoute: typeof PesanRoute
  TerimaRoute: typeof TerimaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terima': {
      id: '/terima'
      path: '/terima'
      fullPath: '/terima'
      preLoaderRoute: typeof TerimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesan': {
      id: '/pesan'
      path: '/pesan'
      fullPath: '/pesan'
      preLoaderRoute: typeof PesanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PesanRoute: PesanRoute,
  TerimaRoute: TerimaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
